language: php
php:
  - "7.2"
  - "7.1"
  - "7.0"
  - hhvm

before_install:
  - npm i -g npm

install:
  - composer install --no-dev -o
  - npm install --only=prod

script:
  - npm run-script build

after_script:
  - php ./vendor/bin/php-cs-fixer fix src
