language: php
php:
  - "7.2"

services:
  - docker

before_install:
  - npm i -g npm

install:
  - composer install
  - npm install

before_script:
  - npm run-script build

script:
  - php bin/console doctrine:schema:update --force
  - php bin/console doctrine:fixtures load

after_script:
  - php ./vendor/bin/php-cs-fixer fix src