version: "3"

services:

  #######################################################
  ###                                                 PHP
  #######################################################
  php:
    container_name: ${APP_NAME}-php
    build: docker/php
    user: www-data
    volumes:
      - ${SYMFONY_APP_PATH}:${SYMFONY_DOCKER_PATH}
    env_file:
      - ${ENV_FILE_DIR}

  #######################################################
  ###                                               NGINX
  #######################################################
  nginx:
    container_name: ${APP_NAME}-nginx
    build: docker/nginx
    ports:
      - ${NGINX_PORT_EXPOSE}:${NGINX_PORT}
    links:
      - php
    volumes:
      - ${SYMFONY_APP_PATH}:${SYMFONY_DOCKER_PATH}
    env_file:
      - ${ENV_FILE_DIR}

  #######################################################
  ###                                                NODE
  #######################################################
  node:
    container_name: ${APP_NAME}-node
    build: docker/node
    user: node
    volumes:
      - ${SYMFONY_APP_PATH}:${SYMFONY_DOCKER_PATH}
    env_file:
      - ${ENV_FILE_DIR}
    command: sh -c "npm install && npm start"

  #######################################################
  ###                                             VARNISH
  #######################################################
  varnish:
    container_name: ${APP_NAME}-varnish
    build: docker/varnish
    ports:
      - ${VARNISH_PORT_EXPOSE}:${VARNISH_PORT}
    depends_on:
      - nginx
    links:
      - nginx
    env_file:
      - ${ENV_FILE_DIR}

  #######################################################
  ###                                               REDIS
  #######################################################
  redis:
    container_name: ${APP_NAME}-redis
    image: redis:4-alpine
    ports:
      - ${REDIS_PORT_EXPOSE}:${REDIS_PORT}
    env_file:
      - ${ENV_FILE_DIR}