<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSNdrnXV\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSNdrnXV/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSNdrnXV.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSNdrnXV\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerSNdrnXV\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'SNdrnXV',
    'container.build_id' => 'b36d346e',
    'container.build_time' => 1534863160,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerSNdrnXV');
